import {
  FaBox,
  FaEnvelope,
  FaRegCommentDots,
  FaTicketAlt,
  FaRegHeart,
  // FaTv,
  FaBlender,
  FaMobileAlt,
  FaHeartbeat,
  FaHome,
  FaTshirt,
  FaAppleAlt,
  FaLaptop,
  FaBaby,
  FaGamepad,
  FaMusic,
  FaEllipsisH,
} from "react-icons/fa";

export const links = [
  {
    id: 1,
    url: "/",
    text: "Order",
    icon: FaBox,
  },
  {
    id: 2,
    url: "/",
    text: "Inbox",
    icon: FaEnvelope,
  },
  {
    id: 3,
    url: "/",
    text: "Pending Reviews",
    icon: FaRegCommentDots,
  },
  {
    id: 4,
    url: "/",
    text: "Voucher",
    icon: FaTicketAlt,
  },
  {
    id: 5,
    url: "/",
    text: "Wishlist",
    icon: FaRegHeart,
  },
];
export const helpData = [
  {
    id: 1,
    url: "/",
    text: "Help Center",
  },
  {
    id: 2,
    url: "/",
    text: "Place an order",
  },
  {
    id: 3,
    url: "/",
    text: "Payment options",
  },
  {
    id: 4,
    url: "/",
    text: "Track an order",
  },
  {
    id: 5,
    url: "/",
    text: "Cancel an order",
  },
  {
    id: 6,
    url: "/",
    text: "Returns & Refunds",
  },
];

export const menu = [
  {
    id: 1,
    url: "/appliances",
    text: "Appliances",
    icon: FaBlender,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 2,
    url: "/phones-tablets",
    text: "Phones & Tablets",
    icon: FaMobileAlt,
    submenu: [
      {
        id: "sub4",
        url: "/appliances/Mobile Phones",
        header: "Mobile Phones",
        items: [
          "Smartphones",
          "Android Phones",
          "iPhones",
          "Basic Phones",
          "Refurbished Phones",
          "Rugged Phones",
          "Cordless Telephones",
          "Dual Sim Phones",
        ],
      },
      {
        id: "sub5",
        url: "/appliances/Tablets",
        header: "Tablets",
        items: [
          "iPads",
          "Android Tablets",
          "Educational Tablets",
          "Tablet Accessories",
          "Amazon Fire Tablets",
          "Microsoft Tablets",
        ],
      },
      {
        id: " sub6",
        url: "/appliances/Mobile Accessories",
        header: "Mobile Accessories",
        items: [
          "Accessory Kits",
          "Adapters",
          "Batteries",
          "Battery Chargers",
          "Bluetooth Headsets",
          "Cables",
          "Car Accessories",
          "Chargers",
          "Earphones & Headsets",
          "MicroSD Cards",
          "Screen Protectors",
          "Selfie Sticks & Tripods",
          "Smart Watches",
          "Power Banks",
          "Phone Camera Lenses",
        ],
      },
      {
        id: "sub7",
        url: "/appliances/Mobile Accessories",
        header: "Top Smartphones",
        items: [
          "iPhone 15 & 15 Pro Max",
          "Samsung Galaxy S24 & S24 Ultra",
          "Tecno Spark 20 & 20 Pro",
          "Itel S23 & S23 Plus",
          "Infinix Smart 8",
          "Xiaomi Redmi 13c",
          "Infinix Hot 40i",
          "Tecno Pop 8",
          "Itel A70",
        ],
      },
      {
        id: "sub8",
        url: "/appliances/Mobile Accessories",
        header: "Top Phone Brands",
        items: ["Samsung", "Apple", "Xiaomi", "Itel", "Tecno"],
      },
    ],
  },
  {
    id: 3,
    url: "/health-beauty",
    text: "Health & Beauty",
    icon: FaHeartbeat,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 4,
    url: "/home-office",
    text: "Home & Office",
    icon: FaHome,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 5,
    url: "/electronics",
    text: "Electronics",
    icon: FaAppleAlt,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 6,
    url: "/fashion",
    text: "Fashion",
    icon: FaTshirt,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 7,
    url: "/supermarket",
    text: "Supermarket",
    icon: FaAppleAlt,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 8,
    url: "/computing",
    text: "Computing",
    icon: FaLaptop,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 9,
    url: "/baby-products",
    text: "Baby Products",
    icon: FaBaby,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 10,
    url: "/gaming",
    text: "Gaming",
    icon: FaGamepad,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 11,
    url: "/musical-instruments",
    text: "Musical Instruments",

    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
  {
    id: 12,
    url: "/other-categories",
    text: "Other Categories",
    icon: FaEllipsisH,
    submenu: [
      {
        id: "sub1",
        url: "/appliances/Small Appliances",
        header: "Small Appliances",
        items: [
          "Blenders",
          "Deep Fryers",
          "Juicers",
          "Air Fryers",
          "Rice Cookers",
          "Toasters & Ovens",
          "Microwaves",
          "Bundles",
          "Vacuum Cleaners",
          "Kettles",
          "Yam Pounders",
          "Irons",
          "Electric Cookware",
          "Electric Drink Mixers",
          "Food Processors",
          "Coffee Makers",
          "Electric Pressure Cookers",
        ],
      },
      {
        id: "sub2",
        url: "/appliances/pressing-iron",
        header: "Large Appliances",
        items: [
          "Washing Machines",
          "Fridges",
          "Freezers",
          "Air Conditioners",
          "Heaters",
          "Fans",
          "Air Purifiers",
          "Water Dispensers",
          "Generators & Inverters",
        ],
      },
      {
        id: "sub3",
        url: "/appliances/Home Appliances",
        header: "Home Appliances",
        items: ["Nexus", "Hisense", "Polystar", "TCL"],
      },
    ],
  },
];
import one from "./assets/pic/slider_pics/1.png";
import two from "./assets/pic/slider_pics/8.png";
import three from "./assets/pic/slider_pics/3.png";
import four from "./assets/pic/slider_pics/4.jpg";
import five from "./assets/pic/slider_pics/5.png";
import six from "./assets/pic/slider_pics/6.png";
import seven from "./assets/pic/slider_pics/7.png";
export const slides = [
  {
    id: 1,
    image: one,
    alt: "Appliances Sale",
  },
  {
    id: 2,
    image: two,
    alt: "Phones and Tablets Sale",
  },
  {
    id: 3,
    image: three,
    alt: "Fashion Deals",
  },
  {
    id: 4,
    image: four,
    alt: "Electronics Offer",
  },
  {
    id: 5,
    image: five,
    alt: "Supermarket Discounts",
  },
  {
    id: 6,
    image: six,
    alt: "Supermarket Discounts",
  },
  {
    id: 7,
    image: seven,
    alt: "Supermarket Discounts",
  },
];
import socks from "./assets/pic/flashSale/socks.jpg";
export const gallery = [
  { id: 1, image: socks, text: "Item One" },
  { id: 2, image: socks, text: "Item Two" },
  { id: 3, image: socks, text: "Item Three" },
  { id: 4, image: socks, text: "Item One" },
  { id: 5, image: socks, text: "Item Two" },
  { id: 6, image: socks, text: "Item Three" },
  { id: 7, image: socks, text: "Item One" },
  { id: 8, image: socks, text: "Item Two" },
  { id: 9, image: socks, text: "Item Three" },
  { id: 10, image: socks, text: "Item One" },
  { id: 11, image: socks, text: "Item Two" },
];
import MensTrenchBlazers from "./assets/pic/flashSale/MensTrenchBlazers.jpg";
export const flashsale = [
  {
    id: 1,
    image: MensTrenchBlazers,
    text: "Item One",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 30,
    totalItems: 50,
  },
  {
    id: 2,
    image: MensTrenchBlazers,
    text: "Item Two",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 5,
    totalItems: 50,
  },
  {
    id: 3,
    image: MensTrenchBlazers,
    text: "Item Three",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 20,
    totalItems: 50,
  },
  {
    id: 4,
    image: MensTrenchBlazers,
    text: "Item One",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 40,
    totalItems: 50,
  },
  {
    id: 5,
    image: MensTrenchBlazers,
    text: "Item Two",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 30,
    totalItems: 50,
  },
  {
    id: 6,
    image: MensTrenchBlazers,
    text: "Item Three",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 34,
    totalItems: 50,
  },
  {
    id: 7,
    image: MensTrenchBlazers,
    text: "Item One",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 10,
    totalItems: 50,
  },
  {
    id: 8,
    image: MensTrenchBlazers,
    text: "Item Two",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 48,
    totalItems: 50,
  },
  {
    id: 9,
    image: MensTrenchBlazers,
    text: "Item Three",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 55,
    totalItems: 50,
  },
  {
    id: 10,
    image: MensTrenchBlazers,
    text: "Item One",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 28,
    totalItems: 50,
  },
  {
    id: 11,
    image: MensTrenchBlazers,
    text: "Item Two",
    reducedprice: "₦29,999",
    actualprice: "₦59,999",
    itemsLeft: 30,
    totalItems: 50,
    itemsLeft: 37,
    totalItems: 50,
  },
];
